// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace API_Organizacion.Models;

public partial class Beneficiarios
{
    [Key]
    public Guid idBeneficiario { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string nombre { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string apellidoPaterno { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string apellidoMaterno { get; set; }

    public Guid parentescoId { get; set; }

    public Guid empleadoId { get; set; }

    [ForeignKey("empleadoId")]
    [InverseProperty("Beneficiarios")]
    public virtual Empleados empleado { get; set; }

    [ForeignKey("parentescoId")]
    [InverseProperty("Beneficiarios")]
    public virtual Parentescos parentesco { get; set; }
}