// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace API_Organizacion.Models;

public partial class Empleados
{
    [Key]
    public Guid idEmpleado { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string nombre { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string apellidoPaterno { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string apellidoMaterno { get; set; }

    [Column(TypeName = "date")]
    public DateTime fechaNacimiento { get; set; }

    public int? edad { get; set; }

    [Required]
    public string fotografia { get; set; }

    public double salario { get; set; }

    public Guid puestoId { get; set; }

    [InverseProperty("empleado")]
    public virtual ICollection<Beneficiarios> Beneficiarios { get; set; } = new List<Beneficiarios>();

    [InverseProperty("empleado")]
    public virtual ICollection<Usuarios> Usuarios { get; set; } = new List<Usuarios>();

    [ForeignKey("puestoId")]
    [InverseProperty("Empleados")]
    public virtual Puestos puesto { get; set; }
}