// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace API_Organizacion.Models;

public partial class OrganizacionContext : DbContext
{
    public OrganizacionContext(DbContextOptions<OrganizacionContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Beneficiarios> Beneficiarios { get; set; }

    public virtual DbSet<Empleados> Empleados { get; set; }

    public virtual DbSet<Parentescos> Parentescos { get; set; }

    public virtual DbSet<Puestos> Puestos { get; set; }

    public virtual DbSet<Usuarios> Usuarios { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Beneficiarios>(entity =>
        {
            entity.HasKey(e => e.idBeneficiario).HasName("PK__Benefici__09162CD19545A246");

            entity.Property(e => e.idBeneficiario).HasDefaultValueSql("(newid())");

            entity.HasOne(d => d.empleado).WithMany(p => p.Beneficiarios)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Beneficia__emple__4CA06362");

            entity.HasOne(d => d.parentesco).WithMany(p => p.Beneficiarios)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Beneficia__paren__4BAC3F29");
        });

        modelBuilder.Entity<Empleados>(entity =>
        {
            entity.HasKey(e => e.idEmpleado).HasName("PK__Empleado__5295297C14D5E584");

            entity.Property(e => e.idEmpleado).HasDefaultValueSql("(newid())");

            entity.HasOne(d => d.puesto).WithMany(p => p.Empleados)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Empleados__puest__403A8C7D");
        });

        modelBuilder.Entity<Parentescos>(entity =>
        {
            entity.HasKey(e => e.idParentesco).HasName("PK__Parentes__9FA875F18354485A");

            entity.Property(e => e.idParentesco).HasDefaultValueSql("(newid())");
        });

        modelBuilder.Entity<Puestos>(entity =>
        {
            entity.HasKey(e => e.idPuesto).HasName("PK__Puestos__ADF48F194E7B9A62");

            entity.Property(e => e.idPuesto).HasDefaultValueSql("(newid())");
        });

        modelBuilder.Entity<Usuarios>(entity =>
        {
            entity.HasKey(e => e.idUsuario).HasName("PK__Usuarios__645723A634CA065E");

            entity.Property(e => e.idUsuario).HasDefaultValueSql("(newid())");

            entity.HasOne(d => d.empleado).WithMany(p => p.Usuarios)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Usuarios__emplea__44FF419A");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}