// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace API_Organizacion.Models;

public partial class Puestos
{
    [Key]
    public Guid idPuesto { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string descripcion { get; set; }

    [InverseProperty("puesto")]
    public virtual ICollection<Empleados> Empleados { get; set; } = new List<Empleados>();
}