// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace API_Organizacion.Models;

public partial class Usuarios
{
    [Key]
    public Guid idUsuario { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string usuario { get; set; }

    [Required]
    [StringLength(128)]
    [Unicode(false)]
    public string clave { get; set; }

    public Guid empleadoId { get; set; }

    [ForeignKey("empleadoId")]
    [InverseProperty("Usuarios")]
    public virtual Empleados empleado { get; set; }
}